services:
  - type: web
    name: community-backend
    env: java
    plan: free
    branch: master
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
